### ISSUE TITLE
[1.16.5] Small incompatibility between BannerAdditions 1.5.1 and Savage & Ravage 3.1.0

### ISSUE THREAD

**Issue by smoothuk** [EliteAsian123/BannerAdditions#11]
The mod Savage & Ravage has an alternative way to start a Raid, by burning an Ominous Banner with a Flint & Steel or Fire Charge.  While BannerAdditions is installed, it is impossible to start a Raid this way as the banner cannot be set on fire.

**Comment by EliteAsian123** [comment]
Unfortunately, this will probably always be incompatible unless I make big changes to this mod. I apologize for the inconvenience.
