### ISSUE TITLE
Incompatibility with "More Waterlogging" mod (1.16.1)

### ISSUE THREAD

**Issue by iCeParadox64** [EliteAsian123/BannerAdditions#3]
The [**More Waterlogging**](https://www.curseforge.com/minecraft/mc-mods/more-waterlogging) mod allows many more types of blocks to be waterlogged (much like Bedrock edition), and one of these block types is banners.  
When using More Waterlogging with BannerAdditions, the game fails to load, with the error:  
```
Banner Additions (banneradditions) encountered an error during the load_registries event phase
Invalid vanilla replacement. See log for details.
```
I'd love to use BannerAdditions, but More Waterlogging is a bit more important for me. If possible, please fix this compatibility issue, and if you do please fix it in the 1.16.1 version! So many mods have yet to update past that version, so many people are stuck there until they do.  
I've included a screenshot of the load error, as well as the game log. The only two mods installed here were BannerAdditions and More Waterlogging, game version 1.16.1, Forge version 32.0.108.  
- [ **latest.log**](https://github.com/EliteAsian123/BannerAdditions/files/5411510/latest.log)  

![error](https://user-images.githubusercontent.com/25655781/96643755-0b8d5a80-12f6-11eb-8ecf-c4b550dc6b38.png)

**Comment by EliteAsian123** [comment]
Hello, thanks for the report! I'm first going to have to get access to the source for More Waterlogging to fix this issue. I will contact you when some fixes are on their way. Thanks!

**Comment by Tfarcenim** [comment]
Source is public https://github.com/Tfarcenim/MoreWaterlogging, the issue is caused by BannerAdditions using registry replacement to change how the block works, you will need to use mixins or some other less invasive way of modifying the block if you wish to stay compatible.

**Comment by EliteAsian123** [comment]
Hello! I have released a compatibility update for BannerAdditions on version 1.16.3. I am now working on the same update for 1.16.1. Sorry for the wait!

**Comment by EliteAsian123** [comment]
Hello again! A 1.16.1 compatibility update has been released. Thanks for the bug report!
