### ISSUE TITLE
Incompatibility with banner patterns added by other mods (1.16.1)

### ISSUE THREAD

**Issue by iCeParadox64** [EliteAsian123/BannerAdditions#4]
The mod [**Neapolitan**](https://www.curseforge.com/minecraft/mc-mods/neapolitan) adds many things, including one new banner pattern of a monkey. When using Neapolitan and BannerAdditions together, the monkey pattern doesn't work on banners— I can't even place it in the loom.  
This is a very small bug and isn't gamebreaking by any means, but I thought I'd report it, because I figure if BA is incompatible with *one* mod-added banner pattern, it's probably incompatible with *all* mod-added banner patterns. Unfortunately I can't 100% confirm that, as Neapolitan is the only other mod I personally use that adds a new pattern.  
___
**Without BannerAdditions installed:**
![2020-10-21_17 30 51](https://user-images.githubusercontent.com/25655781/96794061-81172a80-13cb-11eb-877f-e111df507560.png)
**With BannerAdditions installed:**
![2020-10-21_17 34 51](https://user-images.githubusercontent.com/25655781/96794069-84aab180-13cb-11eb-9cde-a0b69989184b.png)

_(Oh and uh, apologies for reporting a new bug immediately after you fixed the last one I reported 😅 Your mod is just the only one of its kind for recent Minecraft versions, so I'd love to help it be the best it can be!)_

**Comment by EliteAsian123** [comment]
Hello thanks for this report! From taking a quick look of [AbnormalsCore](https://github.com/minecraftabnormals/Abnormals-Core)'s code (Neapolitan's main library that allows for more banner patterns to be added) I will probably not be creating a fix for this at this very moment. If more mods use this feature of Abnormal, I will probably try to create a fix for this.

If you *need* to, you could always [create a custom banner pattern](https://github.com/EliteAsian123/BannerAdditions/wiki/Creating-Custom-Banner-Patterns) and set the item as the banner pattern item so you can place it in the loom.

Sorry about that!

**Comment by EliteAsian123** [comment]
Hello! I have found a fix for this issue and I have started work on implementing it on all versions. I will close the issue when it is fixed!
