### ISSUE TITLE
Wiki Suggestion: Advise to Use World Resourcepacks

### ISSUE THREAD

**Issue by ehx-v1** [EliteAsian123/BannerAdditions#5]
Any resourcepack can be loaded as top-level resourcepack for a single world by placing it in the world save folder (the same where the per-world `datapacks` folder is located) as `resources.zip`. This will apply the resourcepack on top of all other resourcepacks upon world loading, make the player unable to remove that resourcepack manually (or put any resourcepack above it), and automatically remove the resourcepack as the respective world is left. Something similar can also be done for servers, although MineCraft will then ask the player for permission to download and apply the resourcepack. Given the nature of datapacks (although I heard 1.16 has a global location for them as well?), this would probably be the best approach, and I suggest it to be the recommended approach as per the Wiki.

**Comment by ehx-v1** [comment]
Oh, and while on the topic of the wiki, another popular image editor is GIMP. You might want to add it before some less friendly people roast you for not listing it.

**Comment by EliteAsian123** [comment]
Thanks for the suggestions! If I'm going to be honest, I've completely forgot about default resource packs, so I've added those to the wiki. If you have any other suggestions, feel free to open another issue!
