### ISSUE TITLE
Small error on the wiki

### ISSUE THREAD

**Issue by ehx-v1** [EliteAsian123/BannerAdditions#6]
In the list of used IDs, you list `diagonal_up_right` as `rd` and `diagonal_right` as `rud`. Logic tells this should be reversed.

I mean, both IDs and hashes are already used either way, but just in case someone uses the list for creating banners through commands (since it's a nice and mostly clean overview).

**Comment by EliteAsian123** [comment]
Hello! I've never noticed this but according to Minecraft's code, this is actually correct:

![image](https://user-images.githubusercontent.com/29520859/104399017-dae84600-551d-11eb-8501-07f67644a172.png)

I'm not sure why this is (probably a mistake) but thanks for telling me anyways!
