### ISSUE TITLE
Crash when rendering entities with banners on main menu with Menu Companions mod

### ISSUE THREAD

**Issue by Fuzss** [EliteAsian123/BannerAdditions#7]
Hi, so one of my users has an issue where all sorts of illagers will sooner or later refuse to render on the main menu. We found that this is caused by patrol leaders which wear a banner. A crash-report also reveals that the error occurs inside of this mod. 

Most issues with Menu Companions arise from the client player and world not being set yet, so maybe this is where this mod fails, too? Would it be possible to add some sort of null check? I have not looked into your code too much to be able to suggest where it might be necessary.

Here is a link with some more information and the crash-report: https://github.com/Fuzss/menucompanions/issues/8#issuecomment-803651539

**Comment by EliteAsian123** [comment]
Thanks for the issue report, I will solve it and release an update when I have some free time!

**Comment by EliteAsian123** [comment]
I was able to fix the bug on the newest 1.16.5 and 1.16.4 versions. Thanks for the bug report!
