### ISSUE TITLE
40x Textures (or higher)

### ISSUE THREAD

**Issue by WACriminalG2** [EliteAsian123/BannerAdditions#9]
Does this mod support higher-resolution banner patterns? Currently a banner is 20px wide, looks like, and I'm curious whether I could implement patterns with more detail by simply scaling the texture up in multiples of 100%.

**Comment by EliteAsian123** [comment]
This should in theory be possible if you scale up the banner pattern texture by 2 times by any power of 2. If you were to scale the texture by 2 times, the base texture itself would be 128x128, meaning the size of the banner would become 40px. This logic can be applied for higher dimensions as well. I have not tested this however, so please tell me if you have any problems!

**Comment by WACriminalG2** [comment]
I'll give it a shot tonight. Just wanted to make sure I wasn't going to blow anything up/this wasn't a known impossibility, LOL.

**Comment by WACriminalG2** [comment]
Yup! Seems to work in at least a basic sense. I'll re-open the issue if I notice any weird behaviors from it in more complex scenarios.
